backend:
  name: git-gateway
  repo: gatewayapps/gatewayengineering-website
  branch: master 

# publish_mode: editorial_workflow
site_url: https://www.gatewayengineering.com/
display_url: https://www.gatewayengineering.com/

media_folder: static/img
public_folder: /img

collections:
      - label: "Reusable Components"
        name: "reusableComponents"
        files:
          - label: "Header Page"
            name: "header"
            file: "src/pages/header/header.md"
            fields:
              - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "header",
              }
              - label: Header Logo
                name: headerLogo
                widget: image
              - label: Links
                name: navigationLinks
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Path, name: path, widget: string }
      - label: "Pages"
        name: "pages"
        files:
          - label: "About"
            name: "about"
            file: "src/pages/about.md"
            fields:
              - {
                  label: "Template Key",
                  name: "templateKey",
                  widget: "hidden",
                  default: "about-page",
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
          - label: "Services Page"
            name: "services"
            file: "src/pages/services.md"
            fields:
              - {
                  label: "Template Key",
                  name: "templateKey",
                  widget: "hidden",
                  default: "services-page",
                }
              - label: Services 
                name: servicesList 
                widget: list
                fields: 
                  - { label: Service, name: serviceName, widget: string }
                  - { label: Service Description, name: serviceDescription, widget: text }
                  - { label: ServiceImage, name: serviceImage, widget: image }
          - label: "Contact"
            name: "contact"
            file: "src/pages/contact.md"
            fields:
              - {
                  label: "Template Key",
                  name: "templateKey",
                  widget: "hidden",
                  default: "contact-page",
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
