backend:
  name: git-gateway
  repo: gatewayapps/gatewayengineering-website
  branch: NETLIFY_CMS_BRANCH

# publish_mode: editorial_workflow
site_url: https://www.gatewayengineering.com/
display_url: https://www.gatewayengineering.com/

media_folder: static/img
public_folder: /img

collections:
      - label: "Reusable Components"
        name: "reusableComponents"
        files:
          - label: "Header"
            name: "header"
            file: "src/pages/header/header.md"
            fields:
              - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "header",
              }
              - label: Header Logo
                name: headerLogo
                widget: image
              - label: Links
                name: navigationLinks
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Path, name: path, widget: string }
          - label: "Footer"
            name: "footer"
            file: "src/pages/footer/footer.md"
            fields:
              - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "footer",
              }
              - label: Footer Logo
                name: footerLogo
                widget: image
              - label: Links
                name: navigationLinks
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Path, name: path, widget: string }
              - label: Copyright
                name: copyright
                widget: string
              - label: Contact Information
                name: contactInformation
                widget: object
                fields:
                  - { label: Email, name: emailAddress, widget: string }
                  - { label: Phone Number, name: phoneNumber, widget: string }
                  - { label: Street Address, name: streetAddress, widget: text }
      - label: "Front Page"
        name: "frontPage"
        files:
          - label: "Hero section"
            name: "heroSection"
            file: "src/pages/hero-section/hero-section.md"
            fields:
              - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "hero-section",
              }
              - label: Hero Background Image
                name: headerBackgroundImage
                widget: image
              - label: Header Text
                name: headerText
                widget: string
              - label: Sub Text
                name: subText
                widget: text
          - label: "Main Content Section"
            name: "mainContentSection"
            file: "src/pages/main-content/main-content.md"
            fields:
              - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "main-content",
              }
              - label: Header Text
                name: headerText
                widget: text
              - label: Sub Text
                name: subText
                widget: text
              - label: Main Image
                name: mainImage
                widget: image
              - label: Services Overview
                name: servicesOverview
                widget: list
                fields:
                  - { label: Service Image, name: serviceImage, widget: image }
                  - { label: Service Title, name: serviceTitle, widget: string }
                  - { label: Service Description, name: serviceDescription, widget: text }
      - label: "Pages"
        name: "pages"
        files:
        - name: about
          label: About Page
          file: src/pages/about.md
          fields:
            - {
                label: Template Key,
                name: templateKey,
                widget: hidden,
                default: about,
            }
            - label: Header Text
              name: headerText
              widget: string
            - label: Sub Text
              name: subText
            - label: About Image
              name: aboutImage
              widget: image
            - label: About Section
              name: aboutSection
              widget: markdown
        - label: "Services Page"
          name: "services"
          file: "src/pages/services.md"
          fields:
            - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "services-page",
              }
            - label: Services 
              name: servicesList 
              widget: list
              fields: 
                - { label: Service, name: serviceName, widget: string }
                - { label: Service Description, name: serviceDescription, widget: text }
                - { label: ServiceImage, name: serviceImage, widget: image }
        - label: "Contact"
          name: "contact"
          file: "src/pages/contact.md"
          fields:
            - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "contact-page",
              }
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Body", name: "body", widget: "markdown" }
